# -*- coding: utf-8 -*-
"""Aula10_Loops.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1STXyDmpNjpJ0SdxsCnV6MAz8_P4gXsEf

# - Loops

- For
"""

# palavra reservada condicao
# loop finito
import time


# iterando percorrendo
# repetições


l =  [1,2,3,4]


for i in range(10):
    produto = input('Digite o id do produto')
    if i == 5:
        break

for i in range (1,11):
  print(i)

# Iterando por uma Lista:

frutas = ["maçã", "banana", "laranja"]
for fruta in frutas:
    print(fruta)

#Iterando por uma String:

palavra = "Python"
for letra in palavra:
    print(letra)

# Iterando por um Dicionário:

pessoa = {"nome": "João", "idade": 30, "cidade": "São Paulo"}
for chave, valor in pessoa.items():
    print(chave, ":", valor)

"""- While"""

# for   -  sim
# while - sim

dados = {
'produtos' : []
}


perg =  input('Deseja comprar? sim ou não ')


while perg == 'sim':
    prod = input('nome do produto: ')
    dados['produtos'].append(prod)

    print(dados)
    perg =  input('Deseja continuar? sim ou não ')
else:
    print('Obrigado volte sempre! ')

contador = 1
while contador <= 5:
     print("Número:", contador)
     contador += 1

c = 10
while c > 0 :
    print(c)
    c  =  c  - 1

# ATIVIDADE 1

# 1 - Faça um programa, utilizando while, que mostre na tela os números de 0 a 1000.

c = 1
while c <= 10:
  print(c)
  c = c + 1

# 2 -  Faça um sistema, utilizando while e listas, que permita o usuário escrever o nome de 10 pessoas e os mostre na tela.

lista = {
'nomes' : []
}

nome = input("Digite um nome: ")

perg =  input('Deseja adicionar mais um nome? Sim ou Não')

while perg == 'sim':
    nom = input('Proximo nome: ')
    lista['nomes'].append(nom)

    print(lista)
    perg =  input('Deseja adicionar mais um nome? Sim ou Não')

else:
    print('Lista finalizada')

lista = {
'nomes' : []
}

c = 0
while c <=10:
    nom = input('Proximo nome: ')
    lista['nomes'].append(nom)
    c = c +1
print(lista)