# -*- coding: utf-8 -*-
"""Aula10_Sistema_Notas.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1dt8BOeVo_lGRpFgjZkehZIpmJv8zmULc
"""

# Crie um sistema de notas alunos, com as seguintes operações:

# - Acesso a conta com condicionais
# - 3 chances de acessar o sistema
# - Após errar 3 x mensagem que diga que a conta bloqueada (senha incorreta)
# - Inserir notas (se Senha correta)
# - Fazer a média
# - Ao finalizar o código, insira na borda do script, no última linha: input(’Digite enter para sair’)

from contextlib import AbstractAsyncContextManager

emails = ["mariana@hotmail.com", '123@gmail.com']
senhas = ['123', '456']

p = input('Deseja acessar o sistema? sim ou não')

while p =="sim":

  for chances in range (3):
    email = input('Digite seu e-mail: ')
    senha = input("digite sua senha: ")
    if senha in senhas and email in emails:

      print()

      print('SISTEMA DE NOTAS: ')

      print()

      nome_aluno = input('Nome do aluno: ')
      n1 = float(input('Nota 1: '))
      n2 = float(input('Nota 2: '))
      n3 = float(input('Nota 3: '))

      media = ((n1 + n2 + n3)/3)
      print('Media;', media)

      print()

      print('Situação do Aluno: ')

      if media >=7:
        print("Aprovado")
        p = input('Deseja realizar a media de outro aluno? sim ou não')

      elif media >=5 and media <7:
        print('Recuparação')
        p = input('Deseja realizar a media de outro aluno? sim ou não')
      else:
        print('Reprovado')
        p = input('Deseja realizar a media de outro aluno? sim ou não')
    else:
        print('Até logo')
  print()


else:
  print('Senha Bloqueada!')


input('Digite enter para sair')