# -*- coding: utf-8 -*-
"""Aula09_MatchCase.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1UQZRbljhmSaLJjKOzDWQYYcDeH-49cle

# -  Match Case
"""

# função semelhante ao IF

# exemplo 1

n = 10
if n == 0:
   print("zero")
else:
   print('Menor ou maior')



n = 0
match n:
    case 0:
        print("é zero")
    case 1:
        print("Menor ou maior")
    case 2:
        print('É dois...')
    case _:
        print('Algo desconhecido')

#  EXERCÍCIOS com match/ case:

# 1: Verificando se o número é par ou ímpar

numero = int(input('Digite um numero: '))

match numero:
  case numero if numero % 2 == 0 and numero >0 :
    print('Par')
  case _:
    print('Impar')

# 2: Verificando se um número é positivo, negativo ou zero

numero = int(input('Digite um numero: '))

match numero:
  case numero if numero > 0:
    print('Positivo')

  case numero if numero < 0:
    print('Negativo')

  case numero if numero == 0:
    print("Zero")

# 3: Verificando se uma string é vazia ou não

texto = input('Digite um texto: ')

match texto:
  case '':
    print(' Vazia')

  case _:
    print('Preenchida')

# 4: Verificando se um número é maior, menor ou igual a 10


numero = int(input('Digite um numero: '))

match numero:
  case numero if numero > 10:
    print('Maior que 10')

  case numero if numero < 10:
    print('Menos que 10')

  case numero if numero == 10:
    print("Igual a 10")

# 5: Classificando uma idade em faixas etárias -  criança(12), adolescente(17), jovem(35), adulto 35 ><64, idoso(65)

idade = int(input('Digite sua idade: '))

match idade:
  case idade if idade >= 65:
    print('Idoso')

  case idade if idade  >= 35 and idade <= 64:
    print('Adulto')

  case idade if idade >= 17 and idade <= 34:
    print("Jovem")

  case idade if idade >= 12 and idade <= 16:
    print('Adolescente')

  case idade if idade <= 11:
    print('Criança')