# -*- coding: utf-8 -*-
"""Adivinhacao.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1vkyhfUkiqbjYqCNn0aATnNIZvsRbclyX

# - Random
"""

import random

aleatorio = random.randint(1,10)
chute = int(input('Chute um numero: '))

if aleatorio == chute:
  print('Acertei em cheio')
  print("o numero é ", aleatorio)

else:
  print('Errou feio!')
  print('O numero é ', aleatorio)