# -*- coding: utf-8 -*-
"""Aula07_TUPLAS_CONJ_DICIO.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Q1FTI_hLb9-Is_OBYeJoNCxdpQxWlD1J

# - TUPLAS - TUPLE
"""

# estrutura de dados semelhante a uma lista, mas com uma diferença fundamental: as tuplas são imutáveis

# v = 10 # 1 dado (VARIAVEIS)
# lista = [1,2,3] # list varios dados (LISTAS)
# tuplas = (1,2,3) # tuple varios dados imutaveis (TUPLAS)
# conjunto = {1,2,3} # set varios dados numeros s/ repetição (CONJUNTOS)
# dicionario = {'key': 'value'} # dict detalhada (DICIONARIOS)

tupla = (1,2,3)
tuplas = 1,2,3
t = tuple(range(1,11))


tupla+=(t,tuplas)


print(tupla)


# sum(t)
# len(t)
# max()
# print(dir(t))

minha_tupla = (1, 2, 3, 4, 5)

print(minha_tupla)

def obter_coordenadas():
    x = 10
    y = 20
    return x, y

coordenadas = obter_coordenadas()
x, y = coordenadas  # Desempacotando os valores da tupla

count(valor): Retorna o número de vezes que um determinado valor aparece na tupla.


tupla = (1, 2, 2, 3, 4, 2)
print(tupla.count(2))  # Saída: 3


index(valor): Retorna o índice da primeira ocorrência de um valor na tupla.


tupla = (1, 2, 3, 4, 5)
print(tupla.index(3))  # Saída: 2


len(tupla): Retorna o número de elementos na tupla.


tupla = (1, 2, 3, 4, 5)
print(len(tupla))  # Saída: 5



sorted(tupla): Retorna uma nova lista ordenada a partir dos elementos da tupla.


tupla = (5, 3, 1, 4, 2)
lista_ordenada = sorted(tupla)
print(lista_ordenada)  # Saída: [1, 2, 3, 4, 5]



max(tupla) e min(tupla): Retorna o maior e o menor valor na tupla, respectivamente.


tupla = (5, 3, 1, 4, 2)
print(max(tupla))  # Saída: 5
print(min(tupla))  # Saída: 1



tuple(iterável): Converte um iterável em uma tupla.


lista = [1, 2, 3]
tupla = tuple(lista)
print(tupla)  # Saída: (1, 2, 3)



unpacking: Permite atribuir os elementos de uma tupla a variáveis individuais.


tupla = (1, 2, 3)
a, b, c = tupla
print(a, b, c)  # Saída: 1 2 3

"""#  - CONJUNTOS - SET"""

# vARIOS DADOS E NUMEROS SEM REPETIÇÃO

conjunto1 = {1, 2, 3, 4}
conjunto2 = {3, 4, 5, 6}

# União
uniao = conjunto1 | conjunto2  # ou conjunto1.union(conjunto2)
print(uniao)  # Saída: {1, 2, 3, 4, 5, 6}

# Interseção
intersecao = conjunto1 & conjunto2  # ou conjunto1.intersection(conjunto2)
print(intersecao)  # Saída: {3, 4}

# Diferença
diferenca = conjunto1 - conjunto2  # ou conjunto1.difference(conjunto2)
print(diferenca)  # Saída: {1, 2}

# Diferença simétrica
dif_simetrica = conjunto1 ^ conjunto2  # ou conjunto1.symmetric_difference(conjunto2)
print(dif_simetrica)  # Saída: {1, 2, 5, 6}

# Verificar subconjunto
print({1, 2}.issubset(conjunto1))  # Saída: True
print(conjunto1.issuperset({1, 2}))  # Saída: True

"""# - DICIONARIO - DICT"""

# Criando um dicionário

usuario = {
    'nome' : 'Paulo',
    'idade':25,
    'endereço': 'rua 10',
    'curso': ('python','js', 'go'),
    'documento':{132132132,1231231321,2123231231,123132132},
    'livros':{
     'taleb':['antifragil','cisne negro'],
     'harari':['homodeus']
    }
    }



estoque = {
'eletronicos':{
'iphone':['17', '15','14'],
'tvs':['samsumg','lg' ],
},
'moveis':{
'mesas':['etna','x'],
'cadeiras':['etan','leroy']
}
}



# Acessando valores no dicionário

print(usuario['nome'])  # Saída: João
print(usuario['idade'])  # Saída: 30


d =  dict(a = 10, b = 20, c = 30)
print(d)

# ## Desafio 1
# Crie um e-commerce com a estrutura de dicionários. Produtos:  Livros, tablets e fones de ouvido
# As ações: Comprar(), Pagar(), mostra o valor da compra


ecommerce = {
'livro':25.15,
'tablet':3000.0,
'fone':500.0
}

carrinho = {     #carrinho vazio sera preenchido com o valor solicitado no input
'produtos':[],   #valores vazio sera preenchido com o valor solicitado no input
'valores':[]
}

produto1 = input('produto: ')
produto2 = input('produto: ')



carrinho['produtos'].append(produto1)    # codigo : adicionar ao carrinho vazio o produto que foi descrito no input
carrinho['produtos'].append(produto2)
carrinho['valores'].append(ecommerce[produto1])    # codigo:  adicionar o valor do produto que foi descrito no input
carrinho['valores'].append(ecommerce[produto2])

print(carrinho)

soma =  sum(carrinho['valores'])


print('Total -  R$', soma)





formas_pagamentos =  ['pix','cc','cd']
print('escolha a  forma de pagamento: ', formas_pagamentos)
escolhe_forma = input('Digite a forma de pagamento: ')
indice = formas_pagamentos.index(escolhe_forma)
print('Forma de pagamento: ', formas_pagamentos[indice])
print('Obrigada volte sempre! ')

