# -*- coding: utf-8 -*-
"""Aula07.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1CgW43OK2Q3KTvi9r6S2HZwpoCCuytTlz

# - OBJETO
"""

# - Listas
# - Tuplas
# - Conjuntos
# - Dicionarios

"""- Listas"""

lista = [1,2,3,4] - # é possivel usar funções com as posições dentro
print(lista[2])

print(lista[3] + lista[2])

# verifica os metodos que posso utilizar
print(dir(lista))

# INSERT - adiciona na posição desejada
lista = [1,2,3,4]
lista.insert(0,'teste')
print(lista)

# EXTEND - adiciona no final da lista
lista.extend([7,8,9])
print(lista)

# APPEND - Adiciona no final da lista
lista.append(100)
print(lista)

"""- Remover dados da lista"""

# remove - remove a partir do valor

lista.remove(2)
print(lista)#

# pop - remeve o ultimo

lista.pop()
print(lista)

# pop(indice) - remove o indice que for indicado

lista.pop(1)
print(lista)

# del - remove a partir do indice

del lista [1]
print(lista)

"""- Metodos e funções que verificam algum dado da lista

- Ações
"""

# Ações
lista = [1,2,3,4]
print(min(lista)) # menos valor da lista
print(max(lista)) # maior valor da lista
print(len(lista)) # contagem de itens dentro da lista
print(lista.count(3)) # contagem de quantos itens tem do valor declarado

# Ordenar Lista

lista = [4.,5,2,3,4]

lista.sort()
print(lista)

lista.sort(reverse=True)
print(lista)

# ordenar a lista /  revertendo a ardem
lista = [4,5,2,3,4]

lista.reverse()
print(lista)

# Sum - somar todos os dados

print(sum(lista))

# copy - copiar lista

x = lista.copy()
print(x)

# Clear - limpar
lista.clear()
print(lista)

# indece - INDEX - posição do objeto

lista = [4,5,2,3,4]
indice = lista.index(4)
print(indice)

# Range

# **start| stop | step by step (pular de quanto em quanto)**

# **list(range (1,11,2))**

# **list(range(10))**

# **list(range(1,101))**

# criar uma lista com valores declarativos

l = list(range(1,201,9))
print(l)

# Exercício 0:Escreva um programa que use a função range() para gerar os números pares de 2 a 20 e, em seguida, imprima cada número.

l1 = list(range(2,21,2))
print(l1)

# Exercício 1: Crie uma lista chamada numeros que contenha os números inteiros de 1 a 10 e imprima-a na tela.

numeros = list(range(1,11))
print(numeros)

# Exercício 2: Acesse e imprima o terceiro elemento da lista `numeros`.

print(numeros[3])

# Exercício 3: Adicione o número 9 à lista numeros e imprima a lista atualizada.

numeros.extend([9])
print(numeros)

# Exercício 4: Remova o número 5 da lista numeros e imprima a lista resultante.

numeros.pop(4)
print(numeros)

# Exercício 5: Crie uma lista chamada carros contendo três nomes de carros diferentes. Em seguida, concatene essa lista com a lista numeros e imprima o resultado.

carros = ['Mobi', 'Corolla', 'City']

print(numeros + carros)