# -*- coding: utf-8 -*-
"""pedra_papel_tesoura.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1EeZNaDomD93dYypxyuywNgxey_CBLC-g
"""

print("Pedra Papel Tesoura")

"""- Random"""

import random

numero_aleatorio = random.randint(1,10)
print(numero_aleatorio)

lista_maquina = ['🪨', '🧻', '✂️']
print(lista_maquina)

lista_maquina = ['🪨', '🧻', '✂️']
chute_maquina = random.choice(lista_maquina)
print(chute_maquina)

minha_lista = ['','🪨', '🧻', '✂️']
print(minha_lista[3])

lista_maquina = ['🪨', '🧻', '✂️']
chute_maquina = random.choice(lista_maquina)

minha_lista = ['','🪨', '🧻', '✂️']
print('Escolha seu icone')
print('1 -  🪨, 2 - 🧻, 3 - ✂️')
meu_chute = int(input('Escolha pelo indice: '))


if chute_maquina == minha_lista[meu_chute]:
    print('**'*10)
    print('EMPATE')
    print('**'*10)
    print('ESCOLHA MAQUINA - ', chute_maquina)
    print('MINHA ESCOLHA - ',minha_lista[meu_chute])

if chute_maquina == '🪨' and minha_lista[meu_chute] == '✂️':
    print('**'*10)
    print('VITÓRIA DA MAQUINA')
    print('**'*10)
    print('ESCOLHA MAQUINA - ', chute_maquina)
    print('MINHA ESCOLHA - ',minha_lista[meu_chute])

if chute_maquina == '✂️' and minha_lista[meu_chute] == '🧻':
    print('**'*10)
    print('VITÓRIA DA MAQUINA')
    print('**'*10)
    print('ESCOLHA MAQUINA - ', chute_maquina)
    print('MINHA ESCOLHA - ',minha_lista[meu_chute])

if chute_maquina == '🧻' and minha_lista[meu_chute] == '🪨':
    print('**'*10)
    print('VITÓRIA DA MAQUINA')
    print('**'*10)
    print('ESCOLHA MAQUINA - ', chute_maquina)
    print('MINHA ESCOLHA - ',minha_lista[meu_chute])


if minha_lista[meu_chute] == '🪨' and chute_maquina == '✂️':
    print('**'*10)
    print('VOCÊ GANHOU!')
    print('**'*10)
    print('ESCOLHA MAQUINA - ', chute_maquina)
    print('MINHA ESCOLHA - ',minha_lista[meu_chute])

if minha_lista[meu_chute] == '✂️' and chute_maquina == '🧻':
    print('**'*10)
    print('VOCÊ GANHOU!')
    print('**'*10)
    print('ESCOLHA MAQUINA - ', chute_maquina)
    print('MINHA ESCOLHA - ',minha_lista[meu_chute])

if minha_lista[meu_chute] == '🧻' and chute_maquina == '🪨':
    print('**'*10)
    print('VOCÊ GANHOU!')
    print('**'*10)
    print('ESCOLHA MAQUINA - ', chute_maquina)
    print('MINHA ESCOLHA - ',minha_lista[meu_chute])