# -*- coding: utf-8 -*-
"""Aula11_try_and_except.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1W8LrbAVRlxfzn19BTH7u1mDEbDSLXXWg

# - Try and Except
"""

def calcular():
    try:

        l = [1,2,3]
        n1  =  10
        n2  =  3
        x  = 100
        print(n1  / n2 + x)
        print(l[n2])

    except ValueError as erro:
        print(erro)
    except ZeroDivisionError as erro:
        print(erro)
    except TypeError as erro:
        print(erro)
    except NameError as erro:
        print(erro)
    except IndexError as erro :
        print(erro)
    else:
        print('Não existe erro...')

    finally:
        print('Fim de carregamento...')

# ZerroDivisionError
calcular()

#Exercício 1: Peça ao usuário para inserir um número e manipule a exceção caso ele insira algo que não seja um número inteiro.


try:
  x = int(input("Digite um valor: "))
  y = int(input("Digite outro valor: "))

  print( x + y )


except:
  print("Digite valores numericos inteiros!")

#Exercício 2: Peça ao usuário para inserir dois números e realize uma operação de divisão. Manipule a exceção caso ocorra um erro na operação  -  ZeroDivisionError.

try:
  x = int(input("Digite um valor: "))
  y = int(input("Digite outro valor: "))

  print( x / y )


except ZeroDivisionError as erro:
  print("Divisão por zero não existe!")

else:
  print('Não existe erro...')

finally:
  print('Fim de carregamento...')

# Exercício 3: Crie uma lista e um índice como entrada e retorne o índice. Manipule a exceção caso o índice seja inválido(caso imprima um indice que não exista na lista).

try:
  l = [1,2,3]
  print(l[4])

except:
  print ('Erro de indice')