# -*- coding: utf-8 -*-
"""Aula08_E-commerce.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1w9ILo4ozrpRkHnqUl6zYXPG7p-b1-DO7

Desafio 1 - E-commerce
"""

# Crie um e-commerce

# cadastrar login
dados = {
'login':[],
'senha':[],
  'produtos': {
      '1': ['Computador Dell', 5000],
      '2': ["Fona Apple", 2000],
      '3': ['Mouse Lenovo', 250],
      '4': ['Monitor Lenovo', 3000]

  }

}

print('CADASTRE-SE: ')
cad_login = input("Cadastre seu login: ")
cad_senha = input("Cadastre sua senha: ")

dados['login'].append(cad_login) # linha para adicionar dados a lista []
dados['senha'].append(cad_senha)

print()

# acessar e-commerce
print('ACESSE A APLICAÇÃO: ')

print()

acesso_login = input('Digite seu login para acessar: ')
acesso_senha = input('Digite sua senha para acessar: ')

if acesso_login == dados['login'][0] and acesso_senha == dados['senha'][0]:
  print("Seja bem vindo ao E-commerce")

  # Verificar a lista de produtos

  print('Produtos: ')
  produto = input(f'''

    {dados['produtos']} - Escolha 1 - 2 - 3 - 4

  ''')

  # Comprar um produto
  carrinho = []
  valores = []

  carrinho.append(dados['produtos'][produto][0])
  valores.append(dados['produtos'][produto][1])
  print(carrinho [0], 'R$ ', valores [0])

  # Pagar o Produto

  soma = sum(valores)
  print('Valor a pagar - R$', soma)
  pag = input('Digite a forma de pagamento')
  print('Forma de pagamento; ', pag)
  print('Obrigada')

else:
  print("Login ou senhas incorretas")
  print('Faça novamente')