# -*- coding: utf-8 -*-
"""Aula08_IF.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/10nS9eXqDEyEPYebPuWNpKQs9XQlmpNrl

# - IF
"""

#elif - se não se ...
# else - senão
# if - se

#CONDICIONAL SIMPLES

idade = 18
if idade >= 18:
    print("Você é maior de idade.")

#CONDICIONAL COMPOSTA

nota = int(input('Digite a nota: '))
if nota >= 90:
    print("Ótimo desempenho!")
elif nota >= 70:
    print("Bom desempenho.")
else:
    print("Melhorar na próxima.")

# EXERCÍCIOS 1: Utilize condicionais

# 1*
# Peça para o usuário digitar um número, verifique se um número é positivo,
# negativo ou zero.

numero = int(input('Digite um numero: '))

if numero >=1:
  print("Positivo")

elif numero == 0:
  print('Zero')

else:
  print("Negativo")

# 2*

# Peça para o usuário digitar a idade, verifique se uma pessoa pode votar com
# base na idade.

idade = int(input("Digite sua idade: "))

if idade >= 18:
  print("Voto obrigatorio")

elif idade == 16:
    print('Voto opcional')

elif idade == 17:
  print('Voto opcional')

else:
  print('Proibido votar!')

# 3*

# Declara uma variável com um número qualquer,
# determine se um número é par ou ímpar.

valor = int(input('Digite um valor: '))

if valor % 2 == 0:
  print("Numero Par")

else:
  print("Numero Impar")

# 4*

# Usuário vai digitar 3  números, para criar um triângulo, verifique se um triângulo
# é equilátero, isósceles ou escaleno

# Um triângulo é chamado de equilátero se todos os lados possuem a mesma medida.
# Um triângulo é chamado de isósceles se dois lados possuem a mesma medida.
# Um triângulo é chamado de escaleno se todos os lados possuem medidas diferentes.

lado1 = int(input("Digite um valor: "))
lado2 = int(input("Digite um valor: "))
lado3 = int(input("Digite um valor: "))

if lado1 == lado2 == lado3 == lado1:
  print("Equilatero")

elif lado1 != lado2 != lado3 != lado1:
  print('Escaleno')

else:
  print("Isosceles")

# 5*

	# Determine se um número é múltiplo de 5 e 7.

valor = int(input('Digite um valor: '))

if valor % 5 == 0:
  print("Multiplo de 5")

elif valor % 7 == 0:
  print("Multiplo de 7")

else:
  print("não é multiplo de 5 ou 7")

# 6*

# Verifique se um número é positivo e maior que 10

valor = int(input('Digite um valor: '))

if valor >= 10 and valor > 0:
  print( "Positivo, maior que 10")

else:
  print("Negativo")

# 7*

# Verifique se um número é divisível por 3 ou 5.

valor = int(input('Digite um valor: '))

if valor % 5 == 0 or valor % 3 == 0:
  print("Divisivel por 3 ou 5")

else:
  print("não é divisivel por 3 ou 5")