# -*- coding: utf-8 -*-
"""Aula12_Funcoes.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1wYqbjXbyT21bDo4q15_6KxEsqF8cDuL9

# - Funções
"""

# def é o que chama a função para funcionar

#TODOS OS CODIGOS ABAIXO REPRESENTAM A MESMA COISA, APENAS SÃO FEITOS DE FORMAS DIFERENTES:

import random


def soma1():
    print(10 + 10)


def soma2():
    n1 = int(input('digite o valor 1: '))
    n2 = int(input('digite o valor 2: '))
    soma  = n1 + n2
    print(soma)


def soma3(n1, n2):
    print(n1 + n2)


# otimização -  é a melhor utilização de uma função

def soma4(n1, n2):
    return n1  + n2



n1 , n2  = 10,10
def soma5():
    print(n1 + n2)


soma1()
soma2()
soma3(10,10)
print(soma4(10,10))
soma5()




soma = soma4(8+8)
print(soma)

# variaveis locais - esta dentro da função

##Dentro da Funções

def soma():
    n = 10
    x = 11
    soma  = n + x
    print(soma)
soma()

# variaveis global - esta fora das funções

##Fora da Função

numero  = 10
numero2 = 15

def soma():
    somando = numero + numero2
    print(somando)

soma()

# criando a função


def soma():
    n1  = float(input('n1: '))
    n2  = float(input('n2: '))
    print('= ', n1+n2)


def sub():
    n1  = float(input('n1: '))
    n2  = float(input('n2: '))
    print('=', n1-n2)


def mult():
    n1  = float(input('n1: '))
    n2  = float(input('n2: '))
    print('= ', n1*n2)


def divi():
    n1  = float(input('n1: '))
    n2  = float(input('n2: '))
    print('=', n1/n2)


def calculadora():
    operacao = input('''
            escolha a operação:
                     +
                     -
                     /
                     *
                    ''')
    if operacao == '+':
       soma()
    elif operacao == '-':
       sub()
    elif operacao == '/':
        divi()
    elif operacao == '*':
        mult()
    else:
        print('Digite algo valido: ')



def loop():
    while True:
        calculadora()


loop()
break

"""- Funções com Parametros"""

def soma (n1, n2):
  print(n1 +n2)

soma(5,6)
soma(23,58)

# Exercício 1: CRIE UMA FUNÇÃO PARA COMPARAR 2 NÚMEROS (par ou impar). UTILIZE VARIÁVEIS LOCAIS.

valor = int(input('Digite um valor: '))

def comparar():
    if valor % 2 == 0:
      print("Numero Par")

    else:
      print("Numero Impar")
      print(comparar)

comparar()

# Exercício 2: CRIE UMA FUNÇÃO PARA MULTIPLICAR 3 NUMEROS.

def mult(n1, n2, n3):
    return n1*n2*n3


mult3 = mult(8,8,1)
print(mult3)

# Exercicio 3: CRIE UMA FUNÇÃO PARA DESCOBRIR O VALOR ELEVADO DE UM NÚMERO.

def potencia(n1, n2):
    return n1**n2


pot = potencia(2,2)
print(pot)

# Exercicio 4: CRIE UMA FUNÇÃO PARA MOSTRAR UMA MENSAGEM PERSONALIZADA NA TELA, SE O USUÁRIO  DIGITAR, 18 ANOS.


idd = int(input('Digite sua idade: '))

def idade():
    if idd >= 18:
      print("Maior de 18 anos")

    else:
      print("Menor de 18 anos")


idade()

# Exercicio 5: DESENVOLVA UMA FUNÇÃO PARA DESCOBRIR A IDADE DE UMA PESSOA




def nascimento():
  nasc = int(input('Digite a sua data de nascimento: '))
  print(2026 - nasc)


nascimento()

# Exercicio 6: DESENVOLVA UMA FUNÇÃO PARA VER SE O BRASIL GANHOU A COPA DE 1999

# ***DESENVOLVA UM SISTEMA DE RESTAURANTE, ONDE O CLIENTE TEM OPÇÃO DE ESCOLHER ENTRE SALADA, MACARRONADA, SANDUICHE, SORVETE.***

# ***1 - Função -  cumprimentar o cliente***

# ***2 - Função - restaurante***

# ***3 - Sugestão utilize listas  e loops***



print()

#  cumprimentar o cliente

def saudacao():
  print('Seja bem vindo!')
  nome = input('Digite seu nome: ')
  print("*****" * 10)
  print('Bem vindo/a ', nome)

  print()

saudacao()




# Verificar a lista de produtos

def restaurante():

  dados = {
    'produtos': {
      '1': ['SALADA', 19.99],
      '2': ["MACARRONADA", 29.99],
      '3': ['SANDUICHE', 14.99],
      '4': ['SORVETE', 9.99]

  }
}

  print('Escolha seu prato: ')
  produto = input(f'''

    {dados['produtos']} - Escolha 1 - 2 - 3 - 4

''')

# Comprar um produto
  carrinho = []
  valores = []

  carrinho.append(dados['produtos'][produto][0])
  valores.append(dados['produtos'][produto][1])
  print("*****" * 10)
  print(carrinho [0], 'R$ ', valores [0])

  print()

  print('Obrigada, se dirija ao balcao para retirar!')


restaurante()