# -*- coding: utf-8 -*-
"""Aula12_Calculo_trab.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1aKLqpp8NjTzpAKIw22h78AyApUSIMHOe

- Calculadora de Calculos Trabalhistas
"""

from colorama import init, Fore, Back, Style

# verificar valor hora

def verificar_valor_hora(carga, salario):
  return salario / carga


# verificar quantidade de horas extras

def quantidade_extra(valor_extra, valor_hora):
  return valor_extra * valor_hora




# calculo do valor da hora extra total

def hora_extra_receber (quantidade, hora_extra):
  return quantidade * hora_extra



# somar com o salario

def salario_bruto(salario, hora_extra_receber):
  return salario + hora_extra_receber




# verificar os descontos: VR e VT

def descontos(salario_bruto, vr, vt):
  return salario_bruto - (vr + vt)




# liquido e o bruto

def salario_liquido(salario_receber):
  return salario_receber




def sistema_rh():

  while True:

    print(Style.BRIGHT + Fore.BLUE + "*****" * 10)
    salario = float(input(' Salario R$: '))
    carga = 220
    print('Verificar o salario a receber: ')
    valor_hora = verificar_valor_hora(carga, salario)
    print('valor hora R$ ', valor_hora)
    print("*****" * 10)
    extra_50 = quantidade_extra(1.5, valor_hora)
    extra_100 = quantidade_extra(2.0, valor_hora)
    print('Extra 50%', extra_50)
    print('Extra 100%', extra_100)
    print('****' * 10)
    quantidade_50 = float(input('Quantidade de extra realizada 50%: '))
    quantidade_100 = float(input('Quantidade de extra realizada 100%: '))

    hora_receber_50 = hora_extra_receber(quantidade_50, extra_50)
    hora_receber_100 = hora_extra_receber(quantidade_100, extra_100)

    print(f'''

        Hora extra 50 % - R$ {hora_receber_50}
        Hora extra 50 % - R$ {hora_receber_100}

    ''')


    print("*****" * 10)

    hora_extra_total = hora_receber_50 + hora_receber_100
    salario_b = salario_bruto(salario, hora_extra_total)
    print('Salario bruto: R$ ', salario_b)

    print("*****" * 10)

    print('Descontos: ')

    salari_liquidoo = descontos(salario_b, 100, 100)

    print (" Salario a receber: ", salari_liquidoo)

    print()

    print("*****" * 10)

    print()

sistema_rh()

