# -*- coding: utf-8 -*-
"""Funcoes_Restaurante.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1F04svrW94cgnI8nDU6p8kyU5dS0JZLTk
"""

# ***DESENVOLVA UM SISTEMA DE RESTAURANTE, ONDE O CLIENTE TEM OPÇÃO DE ESCOLHER ENTRE SALADA, MACARRONADA, SANDUICHE, SORVETE.***

# ***1 - Função -  cumprimentar o cliente***

# ***2 - Função - restaurante***

# ***3 - Sugestão utilize listas  e loops***



print()

#  cumprimentar o cliente

def saudacao():
  print('Seja bem vindo!')
  nome = input('Digite seu nome: ')
  print("*****" * 10)
  print('Bem vindo/a ', nome)

  print()

saudacao()




# Verificar a lista de produtos

def restaurante():

  dados = {
    'produtos': {
      '1': ['SALADA', 19.99],
      '2': ["MACARRONADA", 29.99],
      '3': ['SANDUICHE', 14.99],
      '4': ['SORVETE', 9.99]

  }
}

  print('Escolha seu prato: ')
  produto = input(f'''

    {dados['produtos']} - Escolha 1 - 2 - 3 - 4

''')

# Comprar um produto
  carrinho = []
  valores = []

  carrinho.append(dados['produtos'][produto][0])
  valores.append(dados['produtos'][produto][1])
  print("*****" * 10)
  print(carrinho [0], 'R$ ', valores [0])

  print()

  print('Obrigada, se dirija ao balcao para retirar!')


restaurante()